RBL/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RBL.Models;
using System.Net;
using RBL.Enums;
using System.Security.Cryptography;

namespace RBL.Controllers
{
    [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
    [Authorize]
    [HandleError(View = "Error")]
    public class UserController : BaseController
    {
        // GET: User
        public ActionResult Index()
        {
            var prms = (long?[])Session["permission"];
            if (RBL.Helpers.Utility.turnOffAuth() || (prms == null))
                return RedirectToAction("Login", "Account");
            if (Helpers.Utility.turnOffAuth() || !(prms.Contains((int)Permission.UserEdit) || prms.Contains((int)Permission.UserAdd) || prms.Contains((int)Permission.UserView)))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            var msg = (Session["msg"] as string);
            if ( msg != null)
            {
                ModelState.AddModelError("", msg);
                Session.Remove("msg");
            }
            using (var db = new mobisnuu_rblEntities())
            {
                var list = db.RBL_UserMaster.Join(db.RBL_RoleName, u => u.role_id, r => r.id, (u, r) => new UserList { Id = u.id,Role = r.role_name, Email = u.email, EmpCode = u.emp_code, Mobile = u.phone_no1, Name = u.name, IsActive = u.is_active}).ToList();
                return View(list);
            }
        }


        [HttpGet]
        public ActionResult Create()
        {
            var prms = (long?[])Session["permission"];
            if (RBL.Helpers.Utility.turnOffAuth() || (prms == null))
                return RedirectToAction("Login", "Account");
            if (Helpers.Utility.turnOffAuth() || !prms.Contains((int)Permission.UserAdd))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            using (var db = new mobisnuu_rblEntities())
            {
                var model = new UserComman();
                model.RoleList = db.RBL_RoleName.Where(x=>x.is_active == true).Select(x => new ListItemRoles { Id = x.id, RoleName = x.role_name }).ToList();
                var allRolePermission = db.RBL_RolePermission.Select(x => new { Id = x.id, RoleId = x.role_id,MenuId = x.menu_id }).ToList();
                foreach (var item in model.RoleList)
                {
                    var permissions = allRolePermission.Where(x => x.RoleId == item.Id).Select(x => (long)x.MenuId).ToList();
                    item.permissions = permissions;
                }
                var categorylist = db.RBL_Menu.Where(x => x.parent_id == 2).Select(x => new { Id = x.id, Type = x.action_name }).ToList();
                var temp = new List<KeyValuePair>();
                foreach (var item in categorylist)
                {
                    var id = System.Convert.ToString(item.Id);
                    temp.Add(new KeyValuePair { Id = id, Type = item.Type });
                }
                model.CategoryPermission = temp;
                var filelist = db.RBL_Menu.Where(x => x.parent_id == 5).Select(x => new { Id = x.id, Type = x.action_name }).ToList();
                temp = new List<KeyValuePair>();
                foreach (var item in filelist)
                {
                    var id = System.Convert.ToString(item.Id);
                    temp.Add(new KeyValuePair { Id = id, Type = item.Type });
                }
                model.FilePermission = temp;
                var userlist = db.RBL_Menu.Where(x => x.parent_id == 8).Select(x => new { Id = x.id, Type = x.action_name }).ToList();
                temp = new List<KeyValuePair>();
                foreach (var item in userlist)
                {
                    var id = System.Convert.ToString(item.Id);
                    temp.Add(new KeyValuePair { Id = id, Type = item.Type });
                }
                model.UserPermission = temp;
                return View(model);
            }            
        }


        /// <summary>
        ///  im writing this code at 3:30 am do you think i care about 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserComman model)
        {
            var prms = (long?[])Session["permission"];
            if (RBL.Helpers.Utility.turnOffAuth() || (prms == null))
                return RedirectToAction("Login", "Account");
            if (Helpers.Utility.turnOffAuth() || !prms.Contains((int)Permission.UserAdd))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            
            using (var db = new mobisnuu_rblEntities())
            {
                model.RoleList = db.RBL_RoleName.Where(x => x.is_active == true).Select(x => new ListItemRoles { Id = x.id, RoleName = x.role_name }).ToList();
                var categorylist = db.RBL_Menu.Where(x => x.parent_id == 2).Select(x => new { Id = x.id, Type = x.action_name }).ToList();
                var allRolePermission = db.RBL_RolePermission.Select(x => new { Id = x.id, RoleId = x.role_id, MenuId = x.menu_id }).ToList();
                foreach (var item in model.RoleList)
                {
                    var permissions = allRolePermission.Where(x => x.RoleId == item.Id).Select(x => (long)x.MenuId).ToList();
                    item.permissions = permissions;
                }
                var temp = new List<KeyValuePair>();
                foreach (var item in categorylist)
                {
                    var id = System.Convert.ToString(item.Id);
                    temp.Add(new KeyValuePair { Id = id, Type = item.Type });
                }
                model.CategoryPermission = temp;
                var filelist = db.RBL_Menu.Where(x => x.parent_id == 5).Select(x => new { Id = x.id, Type = x.action_name }).ToList();
                temp = new List<KeyValuePair>();
                foreach (var item in filelist)
                {
                    var id = System.Convert.ToString(item.Id);
                    temp.Add(new KeyValuePair { Id = id, Type = item.Type });
                }
                model.FilePermission = temp;
                var userlist = db.RBL_Menu.Where(x => x.parent_id == 8).Select(x => new { Id = x.id, Type = x.action_name }).ToList();
                temp = new List<KeyValuePair>();
                foreach (var item in userlist)
                {
                    var id = System.Convert.ToString(item.Id);
                    temp.Add(new KeyValuePair { Id = id, Type = item.Type });
                }
                model.UserPermission = temp;
                if (ModelState.IsValid)
                {
                    var sameObj = db.RBL_UserMaster.Where(x => x.email == model.Email || x.phone_no1 == model.Mobile || x.phone_no2 == model.Mobile || x.emp_code == model.EmpCode).FirstOrDefault();
                    var Role = db.RBL_RoleName.Where(x => x.id == model.Role).FirstOrDefault();

                    if (sameObj == null && Role !=null && Role.is_active == true)
                    {
                        var currentTime = DateTime.Now;
                        var currentUserId = (long?)Session["uid"];
                        var newUser = new RBL_UserMaster();
                        newUser.name = model.Name;
                        newUser.email = model.Email;
                        newUser.phone_no1 = model.Mobile;
                        newUser.phone_no2 = model.Mobile;
                        newUser.emp_code = model.EmpCode;
                        newUser.guid = Guid.NewGuid().ToString();
                        newUser.verification_hash = Guid.NewGuid().ToString();
                        newUser.verification_status = true;
                        newUser.is_active = true;
                        newUser.role_id = model.Role;
                        newUser.password = Helpers.Helpers.ComputeHash(model.password, new SHA256CryptoServiceProvider(), currentTime.ToString());
                        newUser.updated_at = currentTime;
                        newUser.created_at = currentTime;
                        newUser.updated_by = currentUserId;
                        newUser.created_by = currentUserId;
                        db.RBL_UserMaster.Add(newUser);
                        db.SaveChanges();
                        Session["msg"] = "Succefully created user " + newUser.name ;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        if (model.Email == sameObj.email)
                            ModelState.AddModelError("", "Same Email exists");
                        if (sameObj.phone_no1 == model.Mobile || sameObj.phone_no2 == model.Mobile)
                            ModelState.AddModelError("", "Same phone exists");
                        if (sameObj.emp_code == model.EmpCode)
                            ModelState.AddModelError("", "Same emp code exists");
                        if (Role == null)
                            ModelState.AddModelError("", "No Role Found for this id");
                        if (Role != null && Role.is_active == false)
                            ModelState.AddModelError("", "Role is not active");
                    }
                }
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Edit(long? id)
        {
            var prms = (long?[])Session["permission"];
            if (RBL.Helpers.Utility.turnOffAuth() || (prms == null))
                return RedirectToAction("Login", "Account");
            if (Helpers.Utility.turnOffAuth() || !prms.Contains((int)Permission.UserEdit))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

           
            if (id != null)
            {

RBL/Views/User/Create.cshtml
@model RBL.Models.UserComman
@using Newtonsoft.Json;

@{
    ViewBag.Title = "Create User";
}

@using (Html.BeginForm("Create", "User", new {  }, FormMethod.Post, new { @class = "form-horizontal", role = "form", autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    
<div class="data-container rbl-add-user-padding-top-10">
    @Html.ValidationSummary(true, "", new { @class = "text-errr" })
    <div class="full-width rbl-margin-bottom-10">
        <div class="col-lg-2">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "form-field-title" })
        </div>
        <div class="col-lg-10 rbl-margin-bottom-25">
            <div class="form-field">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control admin-input", @placeholder = "Enter Name" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-errr" })
                @*<input class="form-control admin-input" id="disabledInput" type="text" placeholder="Enter Name">*@
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="full-width rbl-margin-bottom-10">
        <div class="col-lg-2">
          @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "form-field-title" })
        </div>
        <div class="col-lg-10  rbl-margin-bottom-25">
            <div class="form-field">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control admin-input", @placeholder = "Enter Email ID", autocomplete = "new-password" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-errr" })
                @*<input class="form-control admin-input" id="disabledInput" type="text" placeholder="Enter Email ID">*@
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="full-width rbl-margin-bottom-10">
        <div class="col-lg-2">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "form-field-title" })
        </div>
        <div class="col-lg-10  rbl-margin-bottom-25">
            <div class="form-field">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control admin-input", @placeholder = "Enter Password", autocomplete = "new-password" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-errr" })
                @*<input class="form-control admin-input" id="disabledInput" type="text" placeholder="Enter Password">*@
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="full-width rbl-margin-bottom-10">
        <div class="col-lg-2">
            @Html.LabelFor(model => model.EmpCode, htmlAttributes: new { @class = "form-field-title" })
        </div>
        <div class="col-lg-10 rbl-margin-bottom-25">
            <div class="form-field">
                @Html.EditorFor(model => model.EmpCode, new { htmlAttributes = new { @class = "form-control admin-input", @placeholder = "Enter Desk No." } })
                @Html.ValidationMessageFor(model => model.EmpCode, "", new { @class = "text-errr" })
                @*<input class="form-control admin-input" id="disabledInput" type="text" placeholder="Enter Mobile/Desk No.">*@
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
   <div class="full-width rbl-margin-bottom-10">
        <div class="col-lg-2">
          @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "form-field-title" })
        </div>
        <div class="col-lg-10 rbl-margin-bottom-25">
            <div class="form-field">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control admin-input", @placeholder = "Enter Mobile No." } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-errr" })
                @*<input class="form-control admin-input" id="disabledInput" type="text" placeholder="Enter Mobile/Desk No.">*@
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="full-width rbl-margin-bottom-10">
        <div class="col-lg-2">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "form-field-title" })
        </div>
        <div class="col-lg-10 rbl-margin-bottom-25">
            <div class="form-field">
                <div class="subcategory-dropdown">
                    <div class="input-group-btn search-panel5">
                        <button type="button" class="pdf-dropdown btn-pdf dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <span id="search_concept5">Select Role</span> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            @foreach (var item in Model.RoleList)
                            {
                                <li><a href="#@item.Id" value="@item.Id" data-roles="@JsonConvert.SerializeObject(item.permissions)">@item.RoleName</a></li>
                            }
                        </ul>
                        <br />
                        @Html.HiddenFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-errr" })
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="full-width rbl-margin-bottom-10">
        <div class="col-lg-2">
            <div class="form-field-title"></div>
        </div>

        <div class="col-lg-10">
            <fieldset>
                <div class="add-user-form-field">
                    <div class="table">
                        <div class="cell">
                            @{
                                foreach (var option in Model.CategoryPermission)
                                {
                                    <div class="admin-check-btn" data-toggle="buttons">
                                        <label class="btn btn-default disabled all permission-@option.Id">
                                            <input type="checkbox" name="CategoryManagement" id="CategoryManagement_@option.Id" value="@System.Convert.ToInt32(option.Id)" autocomplete="off">
                                            <span class="glyphicon glyphicon-ok"></span>
                                        </label>
                                        <label for="CategoryManagement_@option.Id" class="admin-check-txt rbl-checkbox-pd-right-87">@option.Type</label>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
                <div class="add-user-form-field">
                    <div class="table">
                        <div class="cell">
                            @{ var isfirst = true;
                                                    foreach (var option in Model.FilePermission)
                                                    {
                                                    <div class="admin-check-btn" data-toggle="buttons">
                                                        <label class="btn btn-default disabled all permission-@option.Id">
                                                            <input type="checkbox" name="FileManagement" id="FileManagement_@option.Id" value="@System.Convert.ToInt32(option.Id)" autocomplete="off">
                                                            <span class="glyphicon glyphicon-ok"></span>
                                                        </label>
                                                        @if (isfirst)
                                                        {
                                                            <label for="FileManagement_@option.Id" class="admin-check-txt">@option.Type</label>
                                                            isfirst = false;
                                                        }
                                                        else
                                                        {
                                                            <label for="FileManagement_@option.Id" class="admin-check-txt rbl-checkbox-pd-right-87">@option.Type</label>
                                                        }

                                                    </div>

                                            }
                                            }
                        </div>
                    </div>
                </div>
                <div class="add-user-form-field">
                    <div class="table">
                        <div class="cell">
                            @{ isfirst = true;
                                foreach (var option in Model.UserPermission)
                                {
                                    <div class="admin-check-btn" data-toggle="buttons">
                                        <label class="btn btn-default disabled all permission-@option.Id">
                                            <input type="checkbox" name="FileManagement" id="FileManagement_@option.Id" value="@System.Convert.ToInt32(option.Id)" autocomplete="off">
                                            <span class="glyphicon glyphicon-ok"></span>
                                        </label>
                                        @if (isfirst)
                                        {
                                            <label for="FileManagement_@option.Id" class="admin-check-txt">@option.Type</label>
                                            isfirst = false;
                                        }
                                        else
                                        {
                                            <label for="FileManagement_@option.Id" class="admin-check-txt rbl-checkbox-pd-right-87">@option.Type</label>
                                        }
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>

                </fieldset>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="full-width">
        <div class="admin-submit-btns rbl-padding-top-botton-15">
            <input type="button" class="admin-submit-btn btn btn-basic btn-lg btn-margin-left-right" value="Back" onclick="window.location='@Url.Content("~/User")'">
            @*  @Html.ActionLink("Back", "Index", "", new { @class = "", @id = "singlebutton" })// "admin-submit-btn btn btn-basic btn-lg"*@
            <input type="reset" value="Reset" class="admin-submit-btn btn btn-basic btn-lg btn-margin-left-right" onclick="resetForm()" />
            <input type="submit" value="Submit" class="admin-submit-btn btn btn-basic btn-lg btn-margin-left-right" id="singlebutton" />
            @*<button id="singlebutton" name="singlebutton" class="admin-submit-btn btn btn-basic btn-lg">
                Save
            </button>*@
        </div>
    </div>
</div>


}

@section Scripts{
@Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function (e) {
        $(".btn-default").click(function (e) { e.stopPropagation(); e.preventDefault(); })
        $('.search-panel5 .dropdown-menu').find('a').click(function(e) {
            e.preventDefault();
            var param = $(this).attr("href").replace("#","");
            var concept = $(this).text();
            var value = $(this).attr("value");
            $("#Role").val(value);
            $('.search-panel5 span#search_concept5').text(concept);
            var allPermisssions = JSON.parse($(this).attr("data-roles"));
            $(".all").removeClass("active");
            var length = allPermisssions.length;
            for (var i = 0; i < length; i++) {
                $(".permission-" + allPermisssions[i]).addClass("active");
            }
//            $('.input-group #search_param').val(param);
        });
    });
</script>
    }

RBL/Views/User/RolesCreate.cshtml
@model RBL.Models.RolesComman
@using RBL.Helpers;

@{
    ViewBag.Title = "Add Role";
}


@using (Html.BeginForm("RolesCreate", "User", FormMethod.Post))
{
    @Html.AntiForgeryToken()

                    <div class="data-container rbl-padding-top-40">
                        <div class="full-width rbl-margin-bottom-10">
                            @Html.ValidationSummary(true, "", new { @class = "text-errr" })
                            <div class="col-lg-2">
                                <div class="form-field-title">Name</div>
                            </div>
                            <div class="col-lg-10">
                                <div class="form-field">
                                    @Html.EditorFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control admin-input", @placeholder = "Enter Name", @id = "disabledInput" } })
                                    @Html.ValidationMessageFor(model => model.RoleName, "", new { @class = "text-errr" })
                                    @*<input class="form-control admin-input" id="disabledInput" type="text" placeholder="Enter Name">*@
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="full-width rbl-margin-bottom-10">
                            <div class="col-lg-2">
                                <div class="form-field-title">Permissions</div>
                            </div>
                            <div class="col-lg-10">
                                <div class="form-field">
                                    <div class="table">
                                        <div class="cell">
                                            @{
                                                foreach (var option in Model.CategoryPermission)
                                                {
                                                    <div class="admin-check-btn" data-toggle="buttons">
                                                        <label class="btn btn-default">
                                                            <input type="checkbox" name="CategoryManagement" id="CategoryManagement_@option.Id" value="@System.Convert.ToInt32(option.Id)" autocomplete="off">
                                                            <span class="glyphicon glyphicon-ok"></span>
                                                        </label>
                                                        <label for="CategoryManagement_@option.Id" class="admin-check-txt rbl-checkbox-pd-right-87">@option.Type</label>
                                                    </div>
                                                }
                                            }
                                            @Html.ValidationMessageFor(model => model.CategoryManagement, "", new { @class = "text-errr" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-field">
                                    <div class="table">
                                        <div class="cell">
                                            @{ var isfirst = true;
                                                    foreach (var option in Model.FilePermission)
                                                    {
                                                    <div class="admin-check-btn" data-toggle="buttons">
                                                        <label class="btn btn-default">
                                                            <input type="checkbox" name="FileManagement" id="FileManagement_@option.Id" value="@System.Convert.ToInt32(option.Id)" autocomplete="off">
                                                            <span class="glyphicon glyphicon-ok"></span>
                                                        </label>
                                                        @if (isfirst)
                                                        {
                                                            <label for="FileManagement_@option.Id" class="admin-check-txt">@option.Type</label>
                                                            isfirst = false;
                                                        }
                                                        else
                                                        {
                                                            <label for="FileManagement_@option.Id" class="admin-check-txt rbl-checkbox-pd-right-87">@option.Type</label>
                                                        }

                                                    </div>
                                                    @*<div>
                                                        @Html.CheckboxGroup(model => model.FileManagement, System.Convert.ToInt32(option.Id));
                                                        @Html.Label("SelectTypeProjec", option.Type)
                                                    </div>*@

                                            }
                                            }
                                            @Html.ValidationMessageFor(model => model.FileManagement, "", new { @class = "text-errr" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-field">
                                    <div class="table">
                                        <div class="cell">
                                            @{ isfirst = true;
                                                foreach (var option in Model.UserPermission)
                                                {
                                                    <div class="admin-check-btn" data-toggle="buttons">
                                                        <label class="btn btn-default">
                                                            <input type="checkbox" name="FileManagement" id="FileManagement_@option.Id" value="@System.Convert.ToInt32(option.Id)" autocomplete="off">
                                                            <span class="glyphicon glyphicon-ok"></span>
                                                        </label>
                                                        @if (isfirst)
                                                        {
                                                            <label for="FileManagement_@option.Id" class="admin-check-txt">@option.Type</label>
                                                            isfirst = false;
                                                        }
                                                        else
                                                        {
                                                            <label for="FileManagement_@option.Id" class="admin-check-txt rbl-checkbox-pd-right-87">@option.Type</label>
                                                        }

                                                    </div>
                                                }
                                            }
                                            @Html.ValidationMessageFor(model => model.FileManagement, "", new { @class = "text-errr" })
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="full-width rbl-add-rol-mar-top-11perc">
                            <div class="admin-submit-btns rbl-padding-top-botton-15">
                                <input type="button" class="admin-submit-btn btn btn-basic btn-lg btn-margin-left-right" value="Back" onclick="window.location='@Url.Content("~/User/RoleIndex")'">
                                @*  @Html.ActionLink("Back", "Index", "", new { @class = "", @id = "singlebutton" })// "admin-submit-btn btn btn-basic btn-lg"*@
                                <input type="reset" value="Reset" class="admin-submit-btn btn btn-basic btn-lg btn-margin-left-right" onclick="resetForm()" />
                                <input type="submit" value="Submit" class="admin-submit-btn btn btn-basic btn-lg btn-margin-left-right" id="singlebutton" />
                                @*<input type="submit" name="submit" value="submit" id="singlebutton" name="singlebutton" class="admin-submit-btn btn btn-basic btn-lg" />
                                @*<button nclick="document.forms[0].submit()">
                                    Submit
                                </button>
                                <button id="singlebutton" name="singlebutton" class="admin-submit-btn btn btn-basic btn-lg">
                                    Reset
                                </button>*@
                            </div>
                        </div>
                    </div>
                    }


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}